version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: gtsb-wp-dckr
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: gtsb-wp-dckr-user
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"

  wordpress:
    depends_on:
      - db
    image: duffn/wordpress-wpgraphql-wpgatsby:latest
    # While pulling the image will be faster, if you like, you can build the
    # image locally, but uncommenting the lines below and commenting out the
    # `image` line above.
    # The image above will be kept up-to-date, however, you can change WPGraphQL
    # and WPGatsby versions below if you build yourself.
    # build:
    #   context: ./wordpress-wpgraphql-wpgatsby
    #   args:
    #     WPGRAPHQL_VERSION: "${WPGRAPHQL_VERSION:-v0.13.3}"
    #     WPGATSBY_VERSION: "${WPGATSBY_VERSION:-v0.4.17}"
    ports:
      - "8001:8001"
    environment:
      WORDPRESS_DB_PASSWORD: gtsb-wp-dckr-user
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_HOST: db:3306
    restart: always
    volumes:
      - wp_data:/var/www/html

  wordpress-cli:
    depends_on:
      - db
      - wordpress
    image: duffn/wpi-cli-gatsby:latest
    # While pulling the image will be faster, if you like, you can build the
    # image locally, but uncommenting the lines below and commenting out the
    # `image` line above.
    # build:
    #   context: ./wp-cli-gatsby
    volumes:
      - wp_data:/var/www/html

  gatsby:
    depends_on:
      - db
      - wordpress
      - wordpress-cli
    build:
      context: ./gatsby
    ports:
      - "8000:8000"
    environment:
      WPGRAPHQL_URL: http://wordpress:8001/?graphql
    restart: always
    volumes:
      - "./gatsby:/app"
      - "/app/node_modules"

volumes:
  db_data:
  wp_data:
